#!/usr/bin/env python

from manimlib.imports import *

class TestScene(Scene):
    def construct(self):
        circle1 = Circle()
        circle1.move_to(np.array([5,0,0]))
        circle2 = Circle()
        circle2.move_to(np.array([-5,0,0]))
        square1 = Square()
        square1.move_to(np.array([-1,0,0]))
        square2 = Square()
        square2.move_to(np.array([1,0,0]))
        self.play(GrowFromCenter(square1,run_time=3),GrowFromCenter(square2,run_time=3))
        self.play(Transform(square1,circle1,run_time=3),Transform(square2,circle2,run_time=3))
        dot1 = Dot(radius=.5)
        self.play(Transform(square1,dot1,run_time=3),Transform(square2,dot1,run_time=3))
        self.play(ShrinkToCenter(square1,run_time=1),ShrinkToCenter(square2,run_time=1))

class CakeSolution1(Scene):
    def construct(self):
        # Title Title Title Title Title
        title1 = TextMobject("Cake Slices")
        self.play(Write(title1,run_time=2))
        self.play(ApplyMethod(title1.shift,UP*3.2))
        self.wait(2)


        # Cake 1 Cake 1 Cake 1 Cake 1 Cake 1
        heading1 = TextMobject("Slice 1")
        heading1.shift(UP*2.5)
        heading1.scale(.75)
        self.play(Write(heading1))
        self.wait(1)

        line1 = Line((0,0,0),(2.02,0,0))
        line2 = Line((0,0,0),(-.390180644,1.961570561,0))
        arc1 = Arc(radius=2,angle=math.radians(101.25))
        arc1.move_to((.8,1.016020907,0))
        arc1.shift(UP*.1+RIGHT*.1+LEFT*1)
        line1.shift(UP*.1+RIGHT*.1+LEFT*1)
        line2.shift(UP*.1+RIGHT*.1+LEFT*1)
        self.play(ShowCreation(line1,run_time=2),ShowCreation(line2,run_time=2),ShowCreation(arc1,run_time=2))
        self.wait(2)


        # Cake 1 Solution Cake 1 Solution Cake 1 Solution Cake 1 Solution Cake 1 Solution
        text1 = TexMobject(r"\text{Radius} = 8")
        text1.move_to((0,-.2,0))
        text1.scale(.6)
        self.play(Write(text1))
        self.wait(2)

        text2 = TexMobject(r"\text{Arc Length} = 4.5 \pi")
        text2.move_to((0,-.6,0))
        text2.scale(.6)
        self.play(Write(text2))
        self.wait(2)

        text3 = TexMobject(r"\text{Circumference} = 2 \cdot \pi \cdot r")
        text3.move_to((0,-1,0))
        text3.scale(.6)
        self.play(Write(text3))
        self.wait(2)
        text4 = TexMobject(r"\text{Circumference} = 2 \cdot \pi \cdot 8")
        text4.move_to((0,-1,0))
        text4.scale(.6)
        self.play(Transform(text3,text4))
        self.wait(2)
        text5 = TexMobject(r"\text{Circumference} = 16 \pi")
        text5.move_to((0,-1,0))
        text5.scale(.6)
        self.play(Transform(text3,text5))
        self.wait(2)

        text6 = TexMobject(r"\frac{\text{Arc Length}}{\text{Circumference}} = \frac{\theta}{360}")
        text6.move_to((0,-1.6,0))
        text6.scale(.6)
        self.play(Write(text6))
        self.wait(2)
        text7 = TexMobject(r"\frac{4.5 \pi}{16 \pi} = \frac{\theta}{360}")
        text7.move_to((0,-1.6,0))
        text7.scale(.6)
        self.play(Transform(text6,text7))
        self.wait(2)
        text8 = TexMobject(r"0.28125 = \frac{\theta}{360}")
        text8.move_to((0,-1.6,0))
        text8.scale(.6)
        self.play(Transform(text6,text8))
        self.wait(2)
        text9 = TexMobject(r"\theta = 101.25")
        text9.move_to((0,-1.4,0))
        text9.scale(.6)
        self.play(Transform(text6,text9))
        self.wait(2)

        text10 = TexMobject(r"\text{Circle Area} = \pi \cdot  r^{2}")
        text10.move_to((0,-1.8,0))
        text10.scale(.6)
        self.play(Write(text10))
        self.wait(2)
        text11 = TexMobject(r"\text{Circle Area} = \pi \cdot  8^{2}")
        text11.move_to((0,-1.8,0))
        text11.scale(.6)
        self.play(Transform(text10,text11))
        self.wait(2)
        text12 = TexMobject(r"\text{Circle Area} = 64 \pi")
        text12.move_to((0,-1.8,0))
        text12.scale(.6)
        self.play(Transform(text10,text12))
        self.wait(2)

        text13 = TexMobject(r"\text{Sector Area} = \frac{\theta}{360} \cdot \text{Total Area}")
        text13.move_to((0,-2.4,0))
        text13.scale(.6)
        self.play(Write(text13))
        self.wait(2)
        text14 = TexMobject(r"\text{Sector Area} = \frac{101.25}{360} \cdot 64 \pi")
        text14.move_to((0,-2.4,0))
        text14.scale(.6)
        self.play(Transform(text13,text14))
        self.wait(2)
        text15 = TexMobject(r"\text{Sector Area} = \frac{9}{32} \cdot 64 \pi")
        text15.move_to((0,-2.4,0))
        text15.scale(.6)
        self.play(Transform(text13,text15))
        self.wait(2)
        text16 = TexMobject(r"\text{Sector Area} = 18 \pi")
        text16.move_to((0,-2.2,0))
        text16.scale(.6)
        self.play(Transform(text13,text16))
        self.wait(10)


        # Cake 2 Cake 2 Cake 2 Cake 2 Cake 2
